### ISSUE TITLE
Generating offline maps

### ISSUE THREAD

**Issue by ybabs** [rlinosaur/gene_alogy#1]
Hi, I came across your repository and I see you are using offline maps in your `map.qml` file. I was wondering if you could explain the steps used to generate our tiles for this map? It would be much appreciated.

**Comment by rlinosaur** [comment]
Hello! Maybe it's not a proper way, but I do these steps:
1. Run the program.
2. Browse map areas with zoom I need. Copy tiles and providers subdir from "cache" directory to "offline_tiles" directory (paths are in map.qml).
3. ...
4. Profit. I can see cached map without internet. Tiles are from "cache" or "offline_tiles".

Map plugin parameters in map.qml do the thing. I suppose it's the same with examples from QT.

I suppose it's quite possible to use any source of OSM tiles with converting of format and filenames. But tiles from cache are enough for my objective.
I also tried to grab tiles with php-script but it seems map providers have some restrictions about such things and i was able to download only few dozens of tiles at once.
I hope it'll help.
Regards.

**Comment by ybabs** [comment]
Ah, I see, thank you. That's what I'm currently doing now as well. I suppose that will have to do for now.  

Kind regards,
